---
- name: Set ansible hostname
  hostname:
        name: "{{ inventory_hostname }}"

- name: Set authorized key took from file
  authorized_key:
        user: "{{ item }}"
        state: present
        key: "{{ lookup('file', ssh_key_path) }}"
  with_items:
        - root
#        - alex

- name: Add nameserver to resolv.conf
  lineinfile:
    path: /etc/resolv.conf
    line: 'nameserver 8.8.8.8'

- name: Upgrade all packages
  yum: 
    name: '*'
    state: latest

- name: Install packages
  yum: 
        name: "{{ item }}"
        state: present
  with_items:
        - mc
        - firewalld

- name: Include selinux.yml (for production)
  include: selinux.yml
  when: develop|bool != true

- name: Stop and disable iptables
  systemd:
        name: iptables
        state: stopped
        enabled: no
  ignore_errors: yes

- name: Start and enable firewalld
  systemd:
        name: firewalld
        state: started
        enabled: yes

- name: Add rule for hhtp
  firewalld:
    service: http
    permanent: true
    state: enabled

- name: Add rule for https
  firewalld:
    service: https
    permanent: true
    state: enabled
  notify: Restart firewalld

