---
- name: install SELinux packages
  yum:
        name: "{{ item }}"
        state: present
  with_items:
        - libselinux-python
        - policycoreutils
        - policycoreutils-python
        - selinux-policy
        - selinux-policy-targeted
        - libselinux-utils
        - setools
        - setools-console

- name: set selinux policy
  selinux:
        policy: targeted
        state: enforcing
  register: sepolicy

- name: reboot system after set selinux policy
  shell: sleep 2 && shutdown -r now "Ansible package updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  when: sepolicy.changed
  register: reboot

- name: wait for the server to restart
  wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
        delay: 10
        timeout: 300
  become: false
  connection: local
  when: reboot.changed

