---
- name: Check if exists site
  stat:
    path: "{{ vhosts_path }}/{{ client_site_name }}/wp-config.php"
  register: wp_config

- name: Execute wp.yml if site isn't exists
  include: wp.yml
  when: wp_config.stat.exists|bool  == false
 
